name: CI

on:
  push:
    tags: [ "*" ]
    branches:
      - 'main'
  pull_request:
    branches: [ "**" ]

jobs:
  deploy-app-on-kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Create kind cluster
#        uses: helm/kind-action@v1.0.0

      
      - name: "Create single k3d Cluster with imported Registry"
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: CICD-test-cluster
          args: >-
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"

      - name: Apply k8s manifests
        run: |
          kubectl apply -f ./k8s/mongo-config.yaml
          kubectl apply -f ./k8s/mongo-secret.yaml
          kubectl apply -f ./k8s/mongo.yaml
          kubectl apply -f ./k8s/webapp.yaml

      - name: List pods and services
        run: |
          kubectl get pods 
          kubectl get services 
          
      - name: Wait for app
        # TODO: If the Pods never become Ready, e.g. because of config or image problems, this will hang until the workflow
        # times out. Should add a timeout condition to the loop.
        run: |
          while [[ $(kubectl get pods -n default -l app=webapp -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done

      - name: Port Forward to Service
        if: steps.lint.outputs.changed == 'true'
        run: 'kubectl port-forward -n default service/webapp-service 3000:3000 &'

      - name: Test App
        run: |
          curl -v localhost:3000
